### ISSUE TITLE
Add x86-64 micro-architecture targets: x86-64-v2, x86-64-v3, and x86-64-v4.

### ISSUE THREAD

**Issue by morrisonlevi** [calebzulawski/multiversion#31] opened 2021-05-03 14:50 UTC
A recent effort has made micro-architecture targets for x86-64. You can see which instructions are included in each level on Wikipedia: https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels.

Making these available as targets would be nice.

**Comment by calebzulawski** [comment] 2021-05-03 15:08
Thanks for indicating your interest in this.  I've planned on implementing it but haven't gotten around to it yet.  This is a duplicate of #25 so definitely looks like a feature I should prioritize

**Comment by calebzulawski** [comment] 2022-12-04 04:56
This has been implemented on master (in fact, you can specify any target CPU now).  Unfortunately, Rust doesn't properly support MOVBE yet, so x86-64-v3 doesn't work.  See the comments in #25 for a bit more info.

**Closed by calebzulawski** 2022-12-04 04:56 UTC
Labels: duplicate, enhancement
